// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package content

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main id=\"content\" role=\"main\"><!-- Hero Section --><div class=\"container space-top-3 space-top-lg-4\"><!-- Title --><div class=\"w-lg-65 text-center mx-lg-auto mb-5 mb-md-9\"><h1>Что мы делаем?</h1></div><!-- End Title --><div class=\"row\"><div class=\"col-md-7\"><div class=\"ml-lg-4\"></div></div></div></div><!-- End Hero Section --><!-- Services Section --><div class=\"container space-1 space-lg-1\"><!-- Title --><div class=\"w-md-80 w-lg-60 text-center mx-md-auto mb-9\"><span class=\"d-block small font-weight-bold text-cap mb-2\">Немного о нас</span><h2>Быстро, чётко, без задержек — это Deliverlands!</h2></div><!-- End Title --><div class=\"container content-space-2 content-space-lg-3\"><div class=\"row justify-content-lg-between\"><div class=\"col-lg-4 mb-5 mb-lg-0\"><h2>Первый заказ курьерской службы «Deliverlands» был выполнен в 2024 году.</h2></div><!-- End Col --><div class=\"col-lg-6\"><p>Мы — молодая, но динамично развивающаяся компания, которая уже активно работает на рынке и меняет его в лучшую сторону для клиентов. Наша доставка работает точно в указанное вами время:<ul><li>Можно начать выполнение заказа уже через несколько минут после оформления.</li><li>Или доставить в точно назначенный день и час — как вам удобно.</li><li>Мы всегда открыты к предложениям клиента и его новым запросам.</li></ul></p></div><!-- End Col --></div><!-- End Row --></div></div><!-- End Services Section --><!-- Services Section --><!-- End Services Section --><!-- Clients Section --><!-- End Clients Section --></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
